version: 2

sources:
  - name: claims_database
    database: CLAIMS_DATABASE
    schema: PUBLIC
    tables:
      - name: raw_claims
        columns:
          - name: provider_number
            tests:
              - not_null

models:
  - name: raw_claims_check
    description: "Checks for null claim IDs in a filtered view"
    columns:
      - name: claim_id
        tests:
          - not_null

  - name: raw_claims
    description: "Raw claims as bronze layer"
  
  - name: silver_claims
    description: "Cleaned claims - silver layer"
    columns:
      - name: claim_id
        tests:
          - not_null

  - name: fact_duplicate_claims
    description: "Gold Layer: Duplicate Claims"

  - name: fact_procedure_cost
    description: "Gold Layer: Procedure Costs"

  - name: fact_underutilized_care
    description: "Gold Layer: Preventive care underutilization"